apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stock-status

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-statefulset.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - cronjob-backup.yaml

commonLabels:
  app.kubernetes.io/name: stock-status
  app.kubernetes.io/managed-by: kustomize
