apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-status-config
  namespace: stock-status-dev
data:
  # Dev-specific configuration
  ALLOWED_ORIGINS: "http://localhost:4200,http://dev.stock-status.example.com"
  LOGGING_LEVEL_ROOT: "DEBUG"
  LOGGING_LEVEL_COM_STOCKSTATUS: "TRACE"
